// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcControl.Server.Data;

#nullable disable

namespace PcControl.server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214211934_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("PcControl.Shared.Models.Computadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TarifaPorHora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Computadoras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Disponible",
                            IpAddress = "",
                            MacAddress = "",
                            Nombre = "PC-01",
                            TarifaPorHora = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Disponible",
                            IpAddress = "",
                            MacAddress = "",
                            Nombre = "PC-02",
                            TarifaPorHora = 2.50m
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Disponible",
                            IpAddress = "",
                            MacAddress = "",
                            Nombre = "PC-03",
                            TarifaPorHora = 2.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
