// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcControl.Server.Data;

#nullable disable

namespace PcControl.server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214223230_AgregarHistorialTienda")]
    partial class AgregarHistorialTienda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("PcControl.Shared.Models.Computadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TarifaPorHora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Computadoras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Disponible",
                            IpAddress = "",
                            MacAddress = "",
                            Nombre = "PC-01",
                            TarifaPorHora = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Disponible",
                            IpAddress = "",
                            MacAddress = "",
                            Nombre = "PC-02",
                            TarifaPorHora = 2.50m
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Disponible",
                            IpAddress = "",
                            MacAddress = "",
                            Nombre = "PC-03",
                            TarifaPorHora = 2.50m
                        });
                });

            modelBuilder.Entity("PcControl.Shared.Models.Configuracion", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Clave");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Clave = "PrecioHora",
                            Valor = "2.50"
                        },
                        new
                        {
                            Clave = "NombreCiber",
                            Valor = "Mi Ciber Lan"
                        });
                });

            modelBuilder.Entity("PcControl.Shared.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreProductoSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("PcControl.Shared.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsServicio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Bebidas",
                            EsServicio = false,
                            Nombre = "Coca Cola 500ml",
                            Precio = 3.50m,
                            Stock = 24
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Servicios",
                            EsServicio = true,
                            Nombre = "Impresión B/N",
                            Precio = 0.50m,
                            Stock = 0
                        });
                });

            modelBuilder.Entity("PcControl.Shared.Models.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputadoraId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaPagado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCalculado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCobrado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("PcControl.Shared.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SesionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("PcControl.Shared.Models.DetalleVenta", b =>
                {
                    b.HasOne("PcControl.Shared.Models.Venta", null)
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcControl.Shared.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
