// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcControl.Server.Data;

#nullable disable

namespace PcControl.server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251218145013_AgregarCamposFaltantes3")]
    partial class AgregarCamposFaltantes3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("PcControl.Shared.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordAcceso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntosFidelidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioAcceso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PcControl.Shared.Models.Computadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteExtra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotaAdmin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TarifaPorHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TiempoLimiteMinutos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Computadoras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Disponible",
                            ImporteExtra = 0m,
                            IpAddress = "",
                            MacAddress = "",
                            Nombre = "PC-01",
                            TarifaPorHora = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Disponible",
                            ImporteExtra = 0m,
                            IpAddress = "",
                            MacAddress = "",
                            Nombre = "PC-02",
                            TarifaPorHora = 2.50m
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Disponible",
                            ImporteExtra = 0m,
                            IpAddress = "",
                            MacAddress = "",
                            Nombre = "PC-03",
                            TarifaPorHora = 2.50m
                        });
                });

            modelBuilder.Entity("PcControl.Shared.Models.Configuracion", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Clave");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Clave = "PrecioHora",
                            Valor = "2.50"
                        },
                        new
                        {
                            Clave = "NombreCiber",
                            Valor = "Mi Ciber Lan"
                        });
                });

            modelBuilder.Entity("PcControl.Shared.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreProductoSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("PcControl.Shared.Models.HistorialSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteExtra")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteTiempo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PcNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCobrado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistorialSesiones");
                });

            modelBuilder.Entity("PcControl.Shared.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("PcControl.Shared.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("PcControl.Shared.Models.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputadoraId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaPagado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCalculado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCobrado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("PcControl.Shared.Models.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("PcControl.Shared.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            NombreCompleto = "Super Administrador",
                            PasswordHash = "admin123",
                            Rol = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PcControl.Shared.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SesionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("PcControl.Shared.Models.DetalleVenta", b =>
                {
                    b.HasOne("PcControl.Shared.Models.Venta", null)
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcControl.Shared.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
